customizations:
  cloudFormationStacks:
    - deploymentTargets:
        accounts:
          - LogArchive
      description: SIEM role provisioning
      name: SIEM-Role
      regions:
      - us-east-1
      runOrder: 2
      template: cloudformation/gcp-role.yaml
      # parameters:
      #  - name: Parameter1
      #    value: Value1
      # - name: Parameter2
      #   value: Value2
      terminationProtection: true
    # - deploymentTargets:
    #     accounts:
    #       - SharedServices
    #   description: Stack containing shared services resources.
    #   name: SharedServicesResources
    #   regions:
    #   - us-east-1
    #   - us-east-2
    #   runOrder: 1
    #   template: cloudformation/SharedServicesStack.yaml
    #   terminationProtection: true
