#########################################################################################################################################################
# For additional configurable services, features, and property descriptions,                                                                            #
# please review class GlobalConfig reference in our TypeDoc:                                                                                            #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/modules/___packages__aws_accelerator_config_lib_models_global_config.html   #
#########################################################################################################################################################
homeRegion: &HOME_REGION us-east-1
enabledRegions:
  - us-east-1
  - us-west-2
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 180
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
terminationProtection: true
enableOptInRegions: false

controlTower:
  enable: true
  landingZone:
    version: "3.3"
    logging:
      loggingBucketRetentionDays: 365
      accessLoggingBucketRetentionDays: 365
      organizationTrail: true
    security:
      enableIdentityCenterAccess: true
  controls: []
logging:
  account: LogArchive
  centralizedLoggingRegion: us-east-1
  cloudtrail:
    enable: false
    organizationTrail: false
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: true
    


