####################################################################################################################################################
# For additional configurable services, features, and property descriptions,                                                                       #
# please review class IAM Config reference in our TypeDoc:                                                                                         #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/modules/___packages__aws_accelerator_config_lib_models_iam_config.html #
####################################################################################################################################################


providers: []

# policySets:
#   - deploymentTargets:
#       organizationalUnits:
#         - Root
#     policies:
#       - name: PaloFirewall-Policy
#         policy: iam-policies/fw-policy.json

roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: EC2-Default-SSM-AD-Role
        instanceProfile: true
        assumedBy:
          - type: service
            principal: ec2.amazonaws.com
        policies:
          awsManaged:
            - AmazonSSMManagedInstanceCore
            - AmazonSSMDirectoryServiceAccess
            - CloudWatchAgentServerPolicy
        boundaryPolicy: Default-Boundary-Policy

      # - name: Backup-Role
      # # This role is utilized by the Backup Plans defined in global-config.yaml
      # # We create this role in every account where we plan to have Backup Plans
      # # and Backup Vaults
      #   assumedBy:
      #     - type: service
      #       principal: backup.amazonaws.com
      #   policies:
      #     awsManaged:
      #       - service-role/AWSBackupServiceRolePolicyForBackup
      #       - service-role/AWSBackupServiceRolePolicyForRestores
      #       - service-role/AWSBackupServiceRolePolicyForS3Backup
      #       - service-role/AWSBackupServiceRolePolicyForS3Restore
groupSets: []
userSets: []
