########################################################################################################################################################
# For additional configurable services, features, and property descriptions,                                                                           #
# please review class Network-Config reference in our TypeDoc:                                                                                         #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/modules/___packages__aws_accelerator_config_lib_models_network_config.html #
########################################################################################################################################################

homeRegion: &HOME_REGION us-east-1

defaultVpc:
  delete: false
  excludeAccounts: []

endpointPolicies: []

centralNetworkServices:
  delegatedAdminAccount: Network
  gatewayLoadBalancers: []
  ipams: []
  networkFirewall:
    firewalls: []
    policies: []
    rules: []
  route53Resolver:
    endpoints: []
    firewallRuleGroups: []
    queryLogs:
      name: accelerator-query-logs
      destinations:
        - cloud-watch-logs
        - s3
      shareTargets:
        organizationalUnits:
          - Root

transitGateways: []
vpcs: []
