homeRegion: &HOME_REGION us-east-1

defaultVpc:
  delete: false
  excludeAccounts: []

endpointPolicies: []

centralNetworkServices:
  delegatedAdminAccount: Network
  gatewayLoadBalancers: []
  ipams: []
  networkFirewall:
    firewalls: []
    policies: []
    rules: []
  route53Resolver:
    endpoints: []
    firewallRuleGroups: []
    queryLogs:
      name: accelerator-query-logs
      destinations:
        - cloud-watch-logs
        - s3
      shareTargets:
        organizationalUnits:
          - Root

transitGateways: []
vpcs: []
